algoritmo "semnome"
// Função : Função
// Autor : Vinicyus
// Data : 17/02/2022
// Seção de Declarações 
var
  NomeAluno, Curso, Turma: Caracter
  Termo: Inteiro
  Mensalidade: Real
inicio
// Seção de Comandos
   NomeAluno <- "João da Silva"
   Curso <- "Engenharia Civil"
   Termo <- 1
   Turma <- "A"
   Mensalidade <- 900.55
   escreval(NomeAluno)
   escreval(Curso)
   escreval("Termo = ",Termo)
   escreval("Turma = ",Turma)
   escreval("Mensalidade = ",Mensalidade)
fimalgoritmo
